### ISSUE TITLE
Full screen issue

### ISSUE THREAD

**Issue by edwhoardo** [dpjudas/UT99VulkanDrv#19]
I am having issues running the game at fullscreen native res (1080p). The screen won't show any image but I can hear the sound in the background.

If I set the resolution to any other, it will just run as borderless in a corner.

**Comment by dpjudas** [comment]
Which UT version are you using? Note that the driver only works for 469c.
Which graphics card are you using?
Have you installed the latest graphics drivers?
What operating system do you have?

Try setting VkExclusiveFullscreen=True or VkExclusiveFullscreen=False in the [VulkanDrv.VulkanRenderDevice] section in UnrealTournament.ini. It is possible only one of the modes are working on your computer.

Another thing you could try is to set Multisample=0. This will turn off multisampling.

And last try set UseVSync to True or False. There's a chance only one of the modes could be working.

For developers only: if you are a developer, you have the option of installing the Vulkan SDK on your computer and then set VkDebug=True. This will activate the vulkan validation layer and will write errors in the UnrealTournament.log if the layer detects that the driver is doing something wrong. Make sure to turn VkDebug off again after testing, since this option is very bad for performance.

**Comment by edwhoardo** [comment]
I am using 469c
2070ti
527.56
Windows 11

Tried multiple ut99 installs including a fresh one and already tried changing the settings you mentioned.

**Comment by chris-mcc** [comment]
Mm, this could be due to the windows scaling setting not being 100%.

Also try going to windowed mode (alt+enter) to see what happens.

**Comment by dpjudas** [comment]
If setting windows scaling to 100% fixes this issue, then 469c really needs a manifest entry in the executable that sets it to be dpi aware.

You can override the application's dpi awareness by selecting properties on UnrealTournament.exe in File Explorer and then in compatibility tab force the DPI:

![image](https://user-images.githubusercontent.com/5136903/217967320-04c050e7-6f2e-42d2-8edd-c86d155fb517.png)

But please only do keep it like this if it actually fixes the issue.

**Comment by dpjudas** [comment]
I tried opening UnrealTournament.exe in a resource viewer and the embedded manifest already sets it to be DPI aware. So I don't think this is the issue, but if it actually does fix anything then please let us know since that is very interesting to know.

**Comment by edwhoardo** [comment]
It was not windows scaling. I tried a new UT install + 469c and it worked.
