### ISSUE TITLE
Everything works but

### ISSUE THREAD

**Issue by giresun27** [dpjudas/UT99VulkanDrv#2]
I like the vulkan renderer everything works but I get framedrops I need a constant 390fps locked which i can get with d3ddrv.
but with vulkan on some maps it dips below 140fps
can this be improved in future releases? just wondering.
on d3d it stays high constantly.
I have a 390hz monitor btw.

**Comment by dpjudas** [comment]
Which maps are you talking about specifically? Community maps or the standard maps? All the standard maps I've tested with have consistently been running at 360 fps vsync locked (I have a 360 hz monitor).

Also which d3ddrv are you referring to? If it's one of the updated 469 drivers then those use a new rendering interface that allows them to get even better performance than what can be achieved through the older 436 interface that vulkandrv uses.

Could the performance in general be improved? Certainly it could, but I don't have any plans for that currently. I mostly wrote vulkandrv to solve a problem I had with d3d10drv stuttering wildly on my machine and to give me some reference for my UTEngine project.

**Comment by giresun27** [comment]
Im talking about the map ctf-klondike  for example yeah i was reffering to the 469 version of d3d9 
I see then I dont know why this is happening on the vulkandrv 
here is the screenshot
<a href="https://ibb.co/4g97Bxk"><img src="https://i.ibb.co/tPk4y5R/Shot00050.png" alt="Shot00050" border="0"></a>
 u can see fps on r ight side

**Comment by giresun27** [comment]
Oke i found something out the framedrops happen on the latest patch 469b
when i use 469a I get 390 without dips.

**Comment by dpjudas** [comment]
The optimizations for the new render device interface probably caused their fallback code for older renderers to get some performance hit. There is a similar problem with the audio devices where announcer voices completely disappear if you use one written for 436.

Ideally vulkandrv would be upgraded to use their new interface, but since 469 is an unofficial community thing and I'm also the author of UTEngine I'm unsure how safe it is for me to do that. I want to maximize the chance that Epic will not have a problem with UTEngine, and if they expect anyone touching the original code to have signed a NDA (that's how they historically been doing it) I'd prefer not to have broken any rules from their point of view.

Especially since I think Epic never released the source code due to it might be co-owned by Digital Extreme making it legally tricky for them to do it without their permission.
